name: AB-API-Docs - Heroku

on:
  push:
    branches: ['master']
jobs:
  build:
    runs-on: [self-hosted, heroku]

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: docker compose build docs --no-cache
      - name: Start Containers
        run: docker compose up docs --detach
      - name: Amend rights to logs
        run: docker exec -d docs sh -c "chown 2001 -R logs && chgrp 2001 -R logs"
      - name: Run Tests
        run: docker exec -t docs sh -c "npm test"
      - name: Decompose Containers
        run: docker compose down
